### ISSUE TITLE
Required game_hash missing from lab

### ISSUE THREAD

**Issue by ryanmeinzer** [learn-co-curriculum/phase-0-quick-tour-of-the-web#3]
Learn mistakenly did not include the required game_hash in this updated/final Hashketball Lab. 

Therefore, one needs to paste their game_hash from the previous Building Hashketball Lab into hashketball.rb for this Lab to perform.

**Comment by lizbur10** [comment]
Hi there! It looks like this issue may have been posted to the wrong lesson/lab so I'm closing it.

Thanks for contributing to the Flatiron School curriculum 💙
