### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kelly-pierce** [learn-co-curriculum/phase-0-quick-tour-of-the-web#9]
This lesson still isn't super clear on how you and your personal computer interact with the client-server model, and particularly how that involves your internet service provider. possible to spend a little more time elaborating on how you and your personal computer interact with the internet, and less time on a largely esoteric example like grocery store price checking?

**Comment by lizbur10** [comment]
Hi @kelly-pierce ! We are currently in the process of revising the SE Prep content. I'm going to leave this comment open so it can be addressed when we get to this lesson.

Thanks for contributing to the Flatiron School curriculum 💙
